Active: "Jebus"

Modes:
  - Name: "Classic"
    SynchronizedPlayers: false
    InitialArmyScore: 1200
    Stages: 
      - RewardsFactor: 1
        DifficultyFactor: 1
        MinDifficultyFactor: 2 
        StartMinDifficulty: 100
        MaxDifficultyFactor: 20
        StartMaxDifficulty: 1000
        PvpBattles: false
        BattlesLimit: 0
        DaysLimit: 0
        WideStdChance: 10
        BattlesCountFactor: 0.5
  
  - Name: "Days_PVP"
    SynchronizedPlayers: false
    InitialArmyScore: 1200
    Stages:
      - RewardsFactor: 3
        DifficultyFactor: 1
        MinDifficultyFactor: 2
        StartMinDifficulty: 100
        MaxDifficultyFactor: 100
        StartMaxDifficulty: 500
        PvpBattles: false
        BattlesLimit: 0
        DaysLimit: 0
        WideStdChance: 15
        BattlesCountFactor: 3

  - Name: "Jebus"
    SynchronizedPlayers: true
    InitialArmyScore: 1200
    Stages:
      - GuardDifficulty: 0
        RewardsFactor: 3
        DifficultyFactor: 1
        MinDifficultyFactor: 2
        StartMinDifficulty: 100
        MaxDifficultyFactor: 30
        StartMaxDifficulty: 500
        PvpBattles: false
        BattlesLimit: 30
        DaysLimit: 20
        WideStdChance: 10
        BattlesCountFactor: 2
      - GuardDifficulty: 15000
        RewardsFactor: 4
        DifficultyFactor: 1
        MinDifficultyFactor: 10
        StartMinDifficulty: 5000
        MaxDifficultyFactor: 100
        StartMaxDifficulty: 30000
        PvpBattles: true
        BattlesLimit: 0
        DaysLimit: 0
        WideStdChance: 15
        BattlesCountFactor: 3
      - GuardDifficulty: 60000
        RewardsFactor: 8
        DifficultyFactor: 1
        MinDifficultyFactor: 20
        StartMinDifficulty: 20000
        MaxDifficultyFactor: 200
        StartMaxDifficulty: 120000
        PvpBattles: true
        BattlesLimit: 0
        DaysLimit: 0
        WideStdChance: 20
        BattlesCountFactor: 4
