MeleeAttack: &MeleeAttack
  Name: "Melee"
  ThumbnailUrl: "sword.png"
  AttackMaxRange: 1
  AttackMinRange: 1
  StayOnly: false
  CounterattacksCount: 1
  CounterattacksPenaltyPercentage: 50
  CanTargetCounterattack: true
  MinDamage: 1
  MaxDamage: 1

RangeAttack: &RangeAttack
  Name: "Range"
  ThumbnailUrl: "sword.png"
  AttackMaxRange: 15
  AttackMinRange: 2
  StayOnly: true
  CounterattacksCount: 0
  CounterattacksPenaltyPercentage: 0
  RangePenalty: true
  RangePenaltyZonesCount: 1
  EnemyInRangeDisablesAttack: 1
  CanTargetCounterattack: false
  MinDamage: 1
  MaxDamage: 1

Units:
  Peasant:
    Name: "Peasant"
    BattleImgUrl: "/resources/Peasant_portrait.png"
    DashboardImgUrl: "/resources/Peasant_portrait.png"
    Value: 8
    Speed: 2
    Health: 1
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 1
        MaxDamage: 1
  
  Pikeman:
    Name: "Pikeman"
    BattleImgUrl: "/resources/Pikeman_portrait.png"
    DashboardImgUrl: "/resources/Pikeman_portrait.png"
    Value: 60              # Approximate value
    Speed: 4
    Health: 10
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 1
        MaxDamage: 3
      
  Archer:
    Name: "Archer"
    BattleImgUrl: "/resources/Archer_portrait.png"
    DashboardImgUrl: "/resources/Archer_portrait.png"
    Value: 100              # Approximate value
    Speed: 4
    Health: 10
    Attacks:
      - <<: *RangeAttack
        MinDamage: 2
        MaxDamage: 3
      - <<: *MeleeAttack
        MinDamage: 1
        MaxDamage: 2
      
  Griffin:
    Name: "Griffin"
    BattleImgUrl: "/resources/Griffin_portrait.png"
    DashboardImgUrl: "/resources/Griffin_portrait.png"
    Value: 200              # Approximate value
    Speed: 6
    Health: 25
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 3
        MaxDamage: 6
      
  Swordsman:
    Name: "Swordsman"
    BattleImgUrl: "/resources/Swordsman_portrait.png"
    DashboardImgUrl: "/resources/Swordsman_portrait.png"
    Value: 300             # Approximate value
    Speed: 5
    Health: 35
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 6
        MaxDamage: 9
      
  Monk:
    Name: "Monk"
    BattleImgUrl: "/resources/Monk_portrait.png"
    DashboardImgUrl: "/resources/Monk_portrait.png"
    Value: 400             # Approximate value
    Speed: 5
    Health: 30
    Attacks:
      - <<: *RangeAttack
        MinDamage: 10
        MaxDamage: 12
      - <<: *MeleeAttack
        MinDamage: 10
        MaxDamage: 12
      
  Cavalier:
    Name: "Cavalier"
    BattleImgUrl: "/resources/Cavalier_portrait.png"
    DashboardImgUrl: "/resources/Cavalier_portrait.png"
    Value: 1000             # Approximate value
    Speed: 7
    Health: 100
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 15
        MaxDamage: 25
    ResourcesDistribution:
      Gold: 4
      Wood: 1
      
  Angel:
    Name: "Angel"
    BattleImgUrl: "/resources/Angel_portrait.png"
    DashboardImgUrl: "/resources/Angel_portrait.png"
    Value: 3500             # Approximate value
    Speed: 12
    Health: 200
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 50
        MaxDamage: 50
    ResourcesDistribution:
      Gold: 6
      Gems: 1
      
  Skeleton:
    Name: "Skeleton"
    BattleImgUrl: "/resources/Skeleton_portrait.png"
    DashboardImgUrl: "/resources/Skeleton_portrait.png"
    Value: 60
    Speed: 4
    Health: 6
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 1
        MaxDamage: 3

  Zombie:
    Name: "Zombie"
    BattleImgUrl: "/resources/Walking_Dead_portrait.png"
    DashboardImgUrl: "/resources/Walking_Dead_portrait.png"
    Value: 90
    Speed: 4
    Health: 20
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 2
        MaxDamage: 3

  Wight:
    Name: "Wight"
    BattleImgUrl: "/resources/Wight_portrait.png"
    DashboardImgUrl: "/resources/Wight_portrait.png"
    Value: 150
    Speed: 5
    Health: 18
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 3
        MaxDamage: 5

  Vampire:
    Name: "Vampire"
    BattleImgUrl: "/resources/Vampire_portrait.png"
    DashboardImgUrl: "/resources/Vampire_portrait.png"
    Value: 300
    Speed: 6
    Health: 40
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 5
        MaxDamage: 8

  Lich:
    Name: "Lich"
    BattleImgUrl: "/resources/Lich_portrait.png"
    DashboardImgUrl: "/resources/Lich_portrait.png"
    Value: 550
    Speed: 6
    Health: 30
    Attacks:
      - <<: *RangeAttack
        MinDamage: 11
        MaxDamage: 13
      - <<: *MeleeAttack
        MinDamage: 6
        MaxDamage: 7

  DreadKnight:
    Name: "Dread Knight"
    BattleImgUrl: "/resources/Black_Knight_portrait.png"
    DashboardImgUrl: "/resources/Black_Knight_portrait.png"
    Value: 1200
    Speed: 9
    Health: 120
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 15
        MaxDamage: 30
    ResourcesDistribution:
      Gold: 4
      Stone: 1

  GhostDragon:
    Name: "Ghost Dragon"
    BattleImgUrl: "/resources/Bone_Dragon_portrait.png"
    DashboardImgUrl: "/resources/Bone_Dragon_portrait.png"
    Value: 3000
    Speed: 14
    Health: 200
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 25
        MaxDamage: 50
    ResourcesDistribution:
      Gold: 6
      Mercury: 1

  Centaur:
    Name: "Centaur"
    BattleImgUrl: "/resources/Centaur_portrait.png"
    DashboardImgUrl: "/resources/Centaur_portrait.png"
    Value: 70
    Speed: 6
    Health: 8
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 2
        MaxDamage: 3

  Dwarf:
    Name: "Dwarf"
    BattleImgUrl: "/resources/Dwarf_portrait.png"
    DashboardImgUrl: "/resources/Dwarf_portrait.png"
    Value: 120
    Speed: 3
    Health: 20
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 2
        MaxDamage: 4

  WoodElf:
    Name: "Wood Elf"
    BattleImgUrl: "/resources/Wood_Elf_portrait.png"
    DashboardImgUrl: "/resources/Wood_Elf_portrait.png"
    Value: 180
    Speed: 5
    Health: 15
    Attacks:
      - <<: *RangeAttack
        MinDamage: 3
        MaxDamage: 5
      - <<: *MeleeAttack
        MinDamage: 2
        MaxDamage: 4

  Pegasus:
    Name: "Pegasus"
    BattleImgUrl: "/resources/Pegasus_portrait.png"
    DashboardImgUrl: "/resources/Pegasus_portrait.png"
    Value: 300
    Speed: 8
    Health: 30
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 5
        MaxDamage: 9

  Dendroid:
    Name: "Dendroid"
    BattleImgUrl: "/resources/Dendroid_portrait.png"
    DashboardImgUrl: "/resources/Dendroid_portrait.png"
    Value: 400
    Speed: 3
    Health: 55
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 10
        MaxDamage: 14

  Unicorn:
    Name: "Unicorn"
    BattleImgUrl: "/resources/Unicorn_portrait.png"
    DashboardImgUrl: "/resources/Unicorn_portrait.png"
    Value: 900
    Speed: 7
    Health: 90
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 18
        MaxDamage: 22
    ResourcesDistribution:
      Gold: 4
      Gems: 1

  GreenDragon:
    Name: "Green Dragon"
    BattleImgUrl: "/resources/Green_Dragon_portrait.png"
    DashboardImgUrl: "/resources/Green_Dragon_portrait.png"
    Value: 3000
    Speed: 10
    Health: 180
    Attacks:
      - <<: *MeleeAttack
        MinDamage: 40
        MaxDamage: 50
    ResourcesDistribution:
      Gold: 6
      Crystal: 1